In [22]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

## Data Collection

In [23]:
df = pd.read_excel("amazon_ecommerce_messy.xlsx")

In [24]:
df

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
0,ORD-0033913,CUST-18283,PROD-118762,Beauty,Books,Car Accessories,2397.287801,5,15,2025-10-09 18:07:25.816000,...,226,Pending,43,NaN,Ahmedabad,NaN,222027,2025-12-23 18:07:28.598000,51,0
1,ORD-0012022-DUP,CUST-26624,NaN,Automotive,NaN,UNKNOWN,3109.077693,4,5,2026-01-10 18:07:25.780000,...,108,MAYBE,23,Male,CITY,Delhi,XXXX,2025-05-29 18:07:28.563000,21,MAYBE
2,ORD-0073409,CUST-13485,PROD-890878,Fashion,Beauty,Car Accessories,2943.496217,5,10,2026-03-29 18:07:25.882000,...,1,NaN,48,NaN,Pune,NaN,808667,2022-12-26 18:07:28.658000,12,1
3,NaN,CUST-48461,PROD-446550,Home & Kitchen,Toys,NaN,2903.444083,5,25,2025-07-22 18:07:25.910000,...,189,MAYBE,68,NaN,Kolkata,Tamil Nadu,811679,2026-03-09 18:07:28.685000,88,NaN
4,ORD-0038507,CUST-37022,PROD-622689,Automotive,Electronics,Shoes,3766.788567,6,150,2025-11-21 18:07:25.823000,...,13,NaN,49,M,Chennai,UNKNOWN,875923,2023-07-13 18:07:28.605000,48,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106995,ORD-0032500,CUST-27144,PROD-613824,Books,Auto,Smartphones,3913.50899,1,-10,Invalid Date,...,263,NaN,22,Male,CITY,UNKNOWN,218743,2025-03-18 18:07:28.596000,8,Yes
106996,ORD-0028983,CUST-18202,PROD-922459,Home & Kitchen,NaN,Bedding,1050.273505,2,0,2026-03-31 18:07:25.808000,...,169,No,65,F,Mumbai,West Bengal,320617,2024-05-14 18:07:28.590000,10,Yes
106997,ORD-0079887,CUST-07550,PROD-535720,Automotive,Home,Car Accessories,4953.305439,4,-10,2025-06-16 18:07:25.892000,...,32,Yes,21,NaN,NaN,Karnataka,694855,2025-03-13 18:07:28.668000,95,1
106998,ORD-0064198,CUST-48620,PROD-966889,Home & Kitchen,NaN,UNKNOWN,4870.634878,9,25,2026-01-08 18:07:25.866000,...,231,NaN,37,Male,Pune,Maharashtra,674108,2025-02-27 18:07:28.644000,18,0
106999,ORD-0093995,CUST-22752,PROD-477626,Toys,Sports,Car Accessories,NaN,6,40,2025-06-22 18:07:25.915000,...,289,Yes,39,Female,Chennai,NaN,937460,NaN,85,0

## Data Understanding

In [25]:
df.head()

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
0,ORD-0033913,CUST-18283,PROD-118762,Beauty,Books,Car Accessories,2397.287801,5,15,2025-10-09 18:07:25.816000,...,226,Pending,43,NaN,Ahmedabad,NaN,222027,2025-12-23 18:07:28.598000,51,0
1,ORD-0012022-DUP,CUST-26624,NaN,Automotive,NaN,UNKNOWN,3109.077693,4,5,2026-01-10 18:07:25.780000,...,108,MAYBE,23,Male,CITY,Delhi,XXXX,2025-05-29 18:07:28.563000,21,MAYBE
2,ORD-0073409,CUST-13485,PROD-890878,Fashion,Beauty,Car Accessories,2943.496217,5,10,2026-03-29 18:07:25.882000,...,1,NaN,48,NaN,Pune,NaN,808667,2022-12-26 18:07:28.658000,12,1
3,NaN,CUST-48461,PROD-446550,Home & Kitchen,Toys,NaN,2903.444083,5,25,2025-07-22 18:07:25.910000,...,189,MAYBE,68,NaN,Kolkata,Tamil Nadu,811679,2026-03-09 18:07:28.685000,88,NaN
4,ORD-0038507,CUST-37022,PROD-622689,Automotive,Electronics,Shoes,3766.788567,6,150,2025-11-21 18:07:25.823000,...,13,NaN,49,M,Chennai,UNKNOWN,875923,2023-07-13 18:07:28.605000,48,Yes

In [26]:
df.tail()

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
106995,ORD-0032500,CUST-27144,PROD-613824,Books,Auto,Smartphones,3913.50899,1,-10,Invalid Date,...,263,NaN,22,Male,CITY,UNKNOWN,218743,2025-03-18 18:07:28.596000,8,Yes
106996,ORD-0028983,CUST-18202,PROD-922459,Home & Kitchen,NaN,Bedding,1050.273505,2,0,2026-03-31 18:07:25.808000,...,169,No,65,F,Mumbai,West Bengal,320617,2024-05-14 18:07:28.590000,10,Yes
106997,ORD-0079887,CUST-07550,PROD-535720,Automotive,Home,Car Accessories,4953.305439,4,-10,2025-06-16 18:07:25.892000,...,32,Yes,21,NaN,NaN,Karnataka,694855,2025-03-13 18:07:28.668000,95,1
106998,ORD-0064198,CUST-48620,PROD-966889,Home & Kitchen,NaN,UNKNOWN,4870.634878,9,25,2026-01-08 18:07:25.866000,...,231,NaN,37,Male,Pune,Maharashtra,674108,2025-02-27 18:07:28.644000,18,0
106999,ORD-0093995,CUST-22752,PROD-477626,Toys,Sports,Car Accessories,NaN,6,40,2025-06-22 18:07:25.915000,...,289,Yes,39,Female,Chennai,NaN,937460,NaN,85,0

In [27]:
df.sample(5)

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
24323,ORD-0074849,CUST-36836,PROD-469101,Toys,Sports,Shoes,4535.432877,6,20,2025-06-06 18:07:25.884000,...,472,NaN,74,M,Kolkata,Gujarat,806436,2023-10-18 18:07:28.660000,61,NaN
70843,NaN,NaN,NaN,NaN,-999.99,NaN,-999.99,CORRUPTED,NaN,ERROR,...,-999.99,NaN,###,NaN,12345,NaN,12345,12345,NaN,NaN
25793,ORD-0049708,CUST-13999,PROD-936780,NaN,Books,Laptops,2769.387857,7,25,2026-03-27 18:07:25.842000,...,NaN,No,66,M,Ahmedabad,Delhi,567674,NaN,71,No
48144,ORD-0011795,CUST-36492,PROD-373671,Beauty,Sports,Smartphones,3253.011818,3,15,2026-01-31 18:07:25.779000,...,331,NaN,25,M,Hyderabad,Delhi,368091,2023-09-03 18:07:28.563000,48,NaN
35131,ORD-0087406,CUST-45320,PROD-417810,Sports,Books,UNKNOWN,4116.147807,3,-10,2025-10-11 18:07:25.904000,...,323,No,56,F,Pune,Karnataka,981202,2024-08-22 18:07:28.679000,45,NaN

In [28]:
df.shape

(107000, 25)

In [29]:
df.info

<bound method DataFrame.info of                Order_ID Customer_ID   Product_ID    Product_Name     Category  \
0           ORD-0033913  CUST-18283  PROD-118762          Beauty        Books
1       ORD-0012022-DUP  CUST-26624          NaN      Automotive          NaN
2           ORD-0073409  CUST-13485  PROD-890878         Fashion       Beauty
3                   NaN  CUST-48461  PROD-446550  Home & Kitchen         Toys
4           ORD-0038507  CUST-37022  PROD-622689      Automotive  Electronics
...                 ...         ...          ...             ...          ...
106995      ORD-0032500  CUST-27144  PROD-613824           Books         Auto
106996      ORD-0028983  CUST-18202  PROD-922459  Home & Kitchen          NaN
106997      ORD-0079887  CUST-07550  PROD-535720      Automotive         Home
106998      ORD-0064198  CUST-48620  PROD-966889  Home & Kitchen          NaN
106999      ORD-0093995  CUST-22752  PROD-477626            Toys       Sports

           Sub_Category        Price Quantity Discount_Percent  \
0       Car Accessories  2397.287801        5               15
1               UNKNOWN  3109.077693        4                5
2       Car Accessories  2943.496217        5               10
3                   NaN  2903.444083        5               25
4                 Shoes  3766.788567        6              150
...                 ...          ...      ...              ...
106995      Smartphones   3913.50899        1              -10
106996          Bedding  1050.273505        2                0
106997  Car Accessories  4953.305439        4              -10
106998          UNKNOWN  4870.634878        9               25
106999  Car Accessories          NaN        6               40

                        Order_Date  ... Reviews_Count Return_Status  \
0       2025-10-09 18:07:25.816000  ...           226       Pending
1       2026-01-10 18:07:25.780000  ...           108         MAYBE
2       2026-03-29 18:07:25.882000  ...             1           NaN
3       2025-07-22 18:07:25.910000  ...           189         MAYBE
4       2025-11-21 18:07:25.823000  ...            13           NaN
...                            ...  ...           ...           ...
106995                Invalid Date  ...           263           NaN
106996  2026-03-31 18:07:25.808000  ...           169            No
106997  2025-06-16 18:07:25.892000  ...            32           Yes
106998  2026-01-08 18:07:25.866000  ...           231           NaN
106999  2025-06-22 18:07:25.915000  ...           289           Yes

       Customer_Age Customer_Gender       City        State Pincode  \
0                43             NaN  Ahmedabad          NaN  222027
1                23            Male       CITY        Delhi    XXXX
2                48             NaN       Pune          NaN  808667
3                68             NaN    Kolkata   Tamil Nadu  811679
4                49               M    Chennai      UNKNOWN  875923
...             ...             ...        ...          ...     ...
106995           22            Male       CITY      UNKNOWN  218743
106996           65               F     Mumbai  West Bengal  320617
106997           21             NaN        NaN    Karnataka  694855
106998           37            Male       Pune  Maharashtra  674108
106999           39          Female    Chennai          NaN  937460

                    Customer_Since Total_Orders Loyalty_Member
0       2025-12-23 18:07:28.598000           51              0
1       2025-05-29 18:07:28.563000           21          MAYBE
2       2022-12-26 18:07:28.658000           12              1
3       2026-03-09 18:07:28.685000           88            NaN
4       2023-07-13 18:07:28.605000           48            Yes
...                            ...          ...            ...
106995  2025-03-18 18:07:28.596000            8            Yes
106996  2024-05-14 18:07:28.590000           10            Yes
106997  2025-03-13 18:07:28.668000           95              1
106998  2025-02-27 18:07:28.644000           18              0
106999                         NaN           85              0

[107000 rows x 25 columns]>

In [30]:
df.dtypes

Order_ID            object
Customer_ID         object
Product_ID          object
Product_Name        object
Category            object
Sub_Category        object
Price               object
Quantity            object
Discount_Percent    object
Order_Date          object
Delivery_Date       object
Payment_Method      object
Shipping_Cost       object
Order_Status        object
Customer_Rating     object
Reviews_Count       object
Return_Status       object
Customer_Age        object
Customer_Gender     object
City                object
State               object
Pincode             object
Customer_Since      object
Total_Orders        object
Loyalty_Member      object
dtype: object

In [31]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Product_ID', 'Product_Name', 'Category',
       'Sub_Category', 'Price', 'Quantity', 'Discount_Percent', 'Order_Date',
       'Delivery_Date', 'Payment_Method', 'Shipping_Cost', 'Order_Status',
       'Customer_Rating', 'Reviews_Count', 'Return_Status', 'Customer_Age',
       'Customer_Gender', 'City', 'State', 'Pincode', 'Customer_Since',
       'Total_Orders', 'Loyalty_Member'],
      dtype='object')

In [32]:
df.describe()

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
count,103841,97840.00,100209,95747,85545,96139,101266,102183,96829,102695,...,103217,71509,102319,80130,87417,85447,102708,102327,103268,76322
unique,97516,41391.00,89327,14,13,14,95086,25,15,47448,...,506,9,165,11,14,13,88340,75782,105,10
top,###,-999.99,12345,Toys,Clothing,T-Shirts,CORRUPTED,4,10,Invalid Date,...,-100,Yes,28,Male,Bangalore,Telangana,XXXX,Unknown,-5,0
freq,304,289.00,303,10584,10657,10620,298,11066,9767,3796,...,3181,17557,1828,13217,9715,10664,3743,4182,3122,15143

In [33]:
df.describe(include = 'O')

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
count,103841,97840.00,100209,95747,85545,96139,101266,102183,96829,102695,...,103217,71509,102319,80130,87417,85447,102708,102327,103268,76322
unique,97516,41391.00,89327,14,13,14,95086,25,15,47448,...,506,9,165,11,14,13,88340,75782,105,10
top,###,-999.99,12345,Toys,Clothing,T-Shirts,CORRUPTED,4,10,Invalid Date,...,-100,Yes,28,Male,Bangalore,Telangana,XXXX,Unknown,-5,0
freq,304,289.00,303,10584,10657,10620,298,11066,9767,3796,...,3181,17557,1828,13217,9715,10664,3743,4182,3122,15143

In [34]:
df.describe(include='all')

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
count,103841,97840.00,100209,95747,85545,96139,101266,102183,96829,102695,...,103217,71509,102319,80130,87417,85447,102708,102327,103268,76322
unique,97516,41391.00,89327,14,13,14,95086,25,15,47448,...,506,9,165,11,14,13,88340,75782,105,10
top,###,-999.99,12345,Toys,Clothing,T-Shirts,CORRUPTED,4,10,Invalid Date,...,-100,Yes,28,Male,Bangalore,Telangana,XXXX,Unknown,-5,0
freq,304,289.00,303,10584,10657,10620,298,11066,9767,3796,...,3181,17557,1828,13217,9715,10664,3743,4182,3122,15143

## Data Quality Assessment

In [35]:
df.isnull().sum()

Order_ID             3159
Customer_ID          9160
Product_ID           6791
Product_Name        11253
Category            21455
Sub_Category        10861
Price                5734
Quantity             4817
Discount_Percent    10171
Order_Date           4305
Delivery_Date        6215
Payment_Method      21543
Shipping_Cost       13807
Order_Status        26976
Customer_Rating     21454
Reviews_Count        3783
Return_Status       35491
Customer_Age         4681
Customer_Gender     26870
City                19583
State               21553
Pincode              4292
Customer_Since       4673
Total_Orders         3732
Loyalty_Member      30678
dtype: int64

In [36]:
df.duplicated().sum()

5000

In [37]:
df[df.duplicated()]

,Order_ID,Customer_ID,Product_ID,Product_Name,Category,Sub_Category,Price,Quantity,Discount_Percent,Order_Date,...,Reviews_Count,Return_Status,Customer_Age,Customer_Gender,City,State,Pincode,Customer_Since,Total_Orders,Loyalty_Member
1869,ORD-0033394,CUST-19995,PROD-807393,Home & Kitchen,NaN,T-Shirts,43.385185,4,0,2026-03-05 18:07:25.815000,...,419,Yes,48,F,Hyderabad,Gujarat,XXXX,2023-01-28 18:07:28.597000,81,NaN
2025,ORD-0042285,CUST-44039,PROD-368120,Books,Toys,Fitness,4358.647767,4,30,2025-08-03 18:07:25.830000,...,59,NaN,53,Female,CITY,NaN,891002,2022-06-11 18:07:28.610000,66,NaN
3202,ORD-0032957,CUST-19611,PROD-133906,Beauty,Sports,Bedding,573.398526,8,-10,2026-01-20 18:07:25.814000,...,247,MAYBE,48,NaN,Mumbai,Tamil Nadu,678353,NaN,35,1
3943,ORD-0013785,CUST-28256,PROD-309235,Fashion,Sports,Shoes,4125.816871,3,0,2025-08-16 18:07:25.783000,...,297,Pending,54,NaN,Delhi,West Bengal,929229,2023-05-18 18:07:28.566000,42,MAYBE
4155,ORD-0007305,CUST-21048,PROD-880710,INVALID,Home,Laptops,4458.1998,7,25,2025-10-16 18:07:25.772000,...,421,No,24,Male,CITY,West Bengal,856883,2022-08-19 18:07:28.556000,76,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106960,ORD-0003785,CUST-10201,PROD-624614,Books,NaN,NaN,1446.382398,6,25,2025-07-06 18:07:25.766000,...,209,NaN,59,M,Mumbai,Tamil Nadu,633406,2025-08-22 18:07:28.551000,-5,1
106966,NaN,CUST-28199,NaN,Sports,Books,UNKNOWN,4676.391681,1,40,2025-08-29 18:07:25.822000,...,27,NaN,45,NaN,Ahmedabad,Tamil Nadu,661120,2025-06-08 18:07:28.603000,66,NaN
106971,ORD-0065936,CUST-15102,PROD-865581,Sports,Home,Bedding,1543.635996,1,20,2025-11-07 18:07:25.869000,...,NaN,NaN,55,NaN,Mumbai,Delhi,161638,2026-02-27 18:07:28.647000,78,MAYBE
106987,ORD-0066306,CUST-48392,PROD-763150,Automotive,Electronics,Car Accessories,1271.38244,3,20,2026-02-02 18:07:25.869000,...,80,Yes,50,Male,CITY,Telangana,577329,2022-09-27 18:07:28.647000,49,MAYBE
106989,ORD-0034544,CUST-41470,PROD-295099,Automotive,Toys,Fitness,1930.291456,1,5,2025-08-03 18:07:25.817000,...,23,NaN,56,Other,NaN,Maharashtra,760254,2024-06-25 18:07:28.599000,72,No

In [38]:
df.nunique()

Order_ID            97516
Customer_ID         41391
Product_ID          89327
Product_Name           14
Category               13
Sub_Category           14
Price               95086
Quantity               25
Discount_Percent       15
Order_Date          47448
Delivery_Date       59100
Payment_Method         13
Shipping_Cost          12
Order_Status           11
Customer_Rating        13
Reviews_Count         506
Return_Status           9
Customer_Age          165
Customer_Gender        11
City                   14
State                  13
Pincode             88340
Customer_Since      75782
Total_Orders          105
Loyalty_Member         10
dtype: int64

In [39]:
df['Return_Status'].unique()

array(['Pending', 'MAYBE', nan, 'Yes', 'No', 'ERROR', 'CORRUPTED', 12345,
       '###', -999.99], dtype=object)

In [40]:
df['Return_Status'].value_counts()

Return_Status
 Yes          17557
 MAYBE        17544
 Pending      17538
 No           17418
 CORRUPTED      318
-999.99         295
 ###            285
 ERROR          282
 12345          272
Name: count, dtype: int64

## Data Cleaning

#### Remove Duplicates

In [43]:
df.duplicated().sum()

5000

In [44]:
df.drop_duplicates(inplace = True)

In [45]:
df.duplicated().sum()

0

In [47]:
Handel Missi

(102000, 25)